###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - streamlit
  - plotly
  - pip
  - pip:
    - streamlit-plotly-events
    - streamlit-aggrid