###### TODO: how use exact version specifiers for all packages ######
name: streamlit-env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - streamlit
  - plotly
  - pip
  - captcha 
  - pyopenms 
  - pip:
    - streamlit-plotly-events
    - streamlit-aggrid